# This is a basic workflow to help you get started with Actions

name: create_new_exposures2

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  schedule:
  - cron: "15 2 * * 1-5"

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}
          
      - name: create_and_checkout_branch
        run: git checkout -b feature/auto-exposure2
      
      - name: make a new file
        run: echo $(date) > test.txt

      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Commit changes
          branch: feature/auto-exposure2
          
      - name: pull-request
        uses: repo-sync/pull-request@v2
        with:
          source_branch: "feature/auto-exposure2"
          destination_branch: "master"  
          github_token: ${{ secrets.GITHUB_TOKEN }}
#       - name: Create Pull Request
#         uses: peter-evans/create-pull-request@v3
#         with: 
#           base: auto-exposure
